services:
  - type: web
    name: gadmar-api
    runtime: node
    plan: free
    buildCommand: yarn install --production=false && yarn build
    startCommand: yarn start:prod
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: development
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_KEY
        sync: false
      - key: CLOUD_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        value: gadmar_product_images
